### ISSUE TITLE
No coverage information was collected, exit without writing coverage information

### ISSUE THREAD

**Issue by j0n4s** [jribble/grunt-jasmine-node-coverage#57] opened 2016-08-22 23:01 UTC
I have this error: "No coverage information was collected, exit without writing coverage information", the problem is caused for update istanbul version 0.4.4 to 0.4.5, how solution this problem?

**Comment by paazmaya** [comment] 2016-08-23 05:14
Minimal working example to reproduce this is needed

**Comment by j0n4s** [comment] 2016-08-23 05:34
I used 0.5.0 version, I detected the error in package istanbul: "0.4", changed your package to specific version "istanbul":"0.4.4", the problem is with "0.4.5", them change "fileset" dependency to "global" dependency and dont working to fileSrc array

**Comment by j0n4s** [comment] 2016-08-23 05:40
for example fileSrc is [src/calculator.js src/calculator2.js src/obj-util.js], in callback don't return files and Object.keys(global[coverageVar]).length === 0 is true, and the error is "No coverage information was collected, exit without writing coverage information", please could change in 0.5.0 version your package json to "istanbul":"0.4.4", this resolve the problem...

**Comment by paazmaya** [comment] 2016-08-23 05:59
Latest version of this plugin is `1.0.0`, please use that.

**Comment by j0n4s** [comment] 2016-08-23 06:04
I need used junit reporter and my test is in jasmine 1.3...  I can not use the latest version , sorry, I try but my dependencies not let me

**Comment by j0n4s** [comment] 2016-08-23 06:06
only can update to 0.5.0 :(

**Comment by nirnatan** [comment] 2016-08-28 22:13
#59

**Comment by paazmaya** [comment] 2016-09-02 10:55
`wontfix` since cannot update to the latest

**Closed by paazmaya** 2016-09-02 10:55 UTC

**Comment by j0n4s** [comment] 2016-09-02 13:42
ok, thanks for your help, I will try to update version
